name:   Node.js CI
 on:
  push:
   branches: 
  -main
   pull_request: 
   branches:
    -main
     jobs:
      build: 
      
      
      runs-on: ubuntu-latest
       strategy: 
       natrix: 
       node-version: [20.x] 
       steps: 
    - name: Checkout repository 
    uses: actions/checkout@v3
      with:
      node-version: $ matrix.node-version >>
